const users = [{
    id: '1',
    name: 'John Doe',
    email: 'john.doe@example.com',
    role: 'ADMIN',
    avatar: '/images/avatar.png',
    familyMembers: [1, 2, 3],
}]

const familyMembers = [
    {
        id: '1',
        name: 'Darth Vader',
        relationship: 'Father',
        healthScore: 90,
        age: 50,
        gender: 'Male',
        weight: 80,
        height: 180,
        bloodType: 'A+',
        avatar: '/images/avatar.png',
        managerId: '1',
        healthEvents: [1, 2, 3],
    },
    {
        id: '2',
        name: 'Leia Organa',
        relationship: 'Mother',
        healthScore: 90,
        age: 45,
        gender: 'Female',
        weight: 60,
        height: 160,
        bloodType: 'B-',
        avatar: '/images/avatar.png',
        managerId: '1',
        healthEvents: [4, 5, 6],
    },
    {
        id: '3',
        name: 'John Doe',
        relationship: 'Self',
        healthScore: 90,
        age: 20,
        gender: 'Male',
        weight: 70,
        height: 170,
        bloodType: 'O+',
        avatar: '/images/avatar.png',
        managerId: '1',
        healthEvents: [7, 8, 9],
    }
]

const healthEvents = [
    {
        id: '1',
        title: 'Checkup',
        type: 'CHECKUP',
        date: '2021-01-01',
        description: 'Checkup',
        avatar: '/images/avatar.png',
        filePath: [],
        fileType: 'IMAGE',
    },
    {
        id: '2',
        title: 'Medication',
        type: 'MEDICATION',
        date: '2021-01-01',
        description: 'Medication',
    },
    {
        id: '3',
        title: 'Symptom',
        type: 'SYMPTOM',
        date: '2021-01-01',
        description: 'Symptom',
    },
    {
        id: '4',
        title: 'Checkup',
        type: 'CHECKUP',
        date: '2021-01-01',
        description: 'Checkup',
    },
    {
        id: '5',
        title: 'Medication',
        type: 'MEDICATION',
        date: '2021-01-01',
        description: 'Medication',
    },
    {
        id: '6',
        title: 'Symptom',
        type: 'SYMPTOM',
        date: '2021-01-01',
        description: 'Symptom',
    },
    {
        id: '7',
        title: 'Checkup',
        type: 'CHECKUP',
        date: '2021-01-01',
        description: 'Checkup',
    },
    {
        id: '8',
        title: 'Medication',
        type: 'MEDICATION',
        date: '2021-01-01',
        description: 'Medication',
    },
    {
        id: '9',
        title: 'Symptom',
        type: 'SYMPTOM',
        date: '2021-01-01',
        description: 'Symptom',
    },
]